input {
  beats {
    port => 5044
    host => "0.0.0.0"
  }
}

filter {
  if [log_type] == "firewall" {
    grok {
      match => { 
        "message" => ".*\[%{DATA:prefix}\].*SRC=%{IP:src_ip} DST=%{IP:dst_ip}.*PROTO=%{WORD:protocol}.*SPT=%{INT:src_port}.*DPT=%{INT:dst_port}.*"
      }
    }
    
    mutate {
      add_field => { "[@metadata][index]" => "firewall-%{firewall}-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://10.0.3.26:9200"]
    index => "%{[@metadata][index]}"
  }
  
  stdout {
    codec => rubydebug
  }
}
