input {
  beats {
    port => 5044
    host => "0.0.0.0"
  }
}

filter {
  if [log_type] == "ids" {
    json {
      source => "message"
      target => "suricata"
    }
    
    if [suricata][event_type] == "alert" {
      mutate {
        add_field => { 
          "alert_signature" => "%{[suricata][alert][signature]}"
          "alert_category" => "%{[suricata][alert][category]}"
          "alert_severity" => "%{[suricata][alert][severity]}"
          "src_ip" => "%{[suricata][src_ip]}"
          "dest_ip" => "%{[suricata][dest_ip]}"
          "src_port" => "%{[suricata][src_port]}"
          "dest_port" => "%{[suricata][dest_port]}"
          "protocol" => "%{[suricata][proto]}"
        }
      }
    }
    
    date {
      match => [ "[suricata][timestamp]", "ISO8601" ]
      target => "@timestamp"
    }
    
    mutate {
      add_field => { "[@metadata][index]" => "suricata-%{ids}-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  if [log_type] == "ids" {
    elasticsearch {
      hosts => ["http://10.0.3.26:9200"]
      index => "%{[@metadata][index]}"
    }
    
    stdout {
      codec => rubydebug
    }
  }
}
