input {
  beats {
    port => 5044
    host => "0.0.0.0"
  }
}

filter {
  # Firewall logs processing
  if [log_type] == "firewall" {
    grok {
      match => { 
        "message" => ".*\[%{DATA:prefix}\].*SRC=%{IP:src_ip} DST=%{IP:dst_ip}.*PROTO=%{WORD:protocol}.*SPT=%{INT:src_port}.*DPT=%{INT:dst_port}.*"
      }
    }
    
    mutate {
      add_field => { "[@metadata][index]" => "firewall-%{firewall}-%{+YYYY.MM.dd}" }
    }
  }

  # IDS logs processing
  if [log_type] == "ids" {
    json {
      source => "message"
      target => "suricata"
    }
    
    if [suricata][event_type] == "alert" {
      mutate {
        add_field => { 
          "alert_signature" => "%{[suricata][alert][signature]}"
          "alert_category" => "%{[suricata][alert][category]}"
          "alert_severity" => "%{[suricata][alert][severity]}"
          "src_ip" => "%{[suricata][src_ip]}"
          "dest_ip" => "%{[suricata][dest_ip]}"
          "src_port" => "%{[suricata][src_port]}"
          "dest_port" => "%{[suricata][dest_port]}"
          "protocol" => "%{[suricata][proto]}"
        }
      }
    }
    
    date {
      match => [ "[suricata][timestamp]", "ISO8601" ]
      target => "@timestamp"
    }
    
    mutate {
      add_field => { "[@metadata][index]" => "suricata-%{ids}-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://172.20.20.3:9200"]
    index => "%{[@metadata][index]}"
  }
  
  stdout {
    codec => rubydebug
  }
}
